const Data = [
  {
    id: 1,
    img: require("./images/img01.jpg"),
    nombre: "BreezeWalk X1",
    desc: "Las BreezeWalk X1 son unas sandalias ligeras y cómodas diseñadas para quienes disfrutan de caminar con el viento en sus pies. Su diseño ergonómico y su suela flexible proporcionan una sensación de frescura y comodidad durante todo el día, perfectas para paseos relajados en la playa o en la piscina",
    precio: 100,
    categoria: "RELAX",
    stock: 3,
  },
  {
    id: 2,
    img: require("./images/img02.jpg"),
    nombre: "SunsetRelax Pro",
    desc: "Las SunsetRelax Pro son sandalias alto rendimiento ideales para los amantes de la playa y la relajación. Con una plantilla acolchada y un diseño resistente al agua, estas chanclas te brindarán el confort necesario para disfrutar de las puestas de sol y las actividades al aire libre.",
    precio: 100,
    categoria: "RELAX",
    stock: 2,
  },
  {
    id: 3,
    img: require("./images/img03.jpg"),
    nombre: "TropicGlide",
    desc: "Las TropicGlide con un toque de estilo tropical y sofisticación. Diseñadas con detalles de diseño exquisitos y materiales de calidad, estas chanclas son la elección perfecta para aquellos que buscan la combinación perfecta entre moda y comodidad en climas cálidos.",
    precio: 100,
    categoria: "RELAX",
    stock: 6,
  },
  {
    id: 4,
    img: require("./images/img04.png"),
    nombre: "UrbanAura",
    desc: "Las UrbanAura son zapatillas versátiles que capturan el espíritu de la vida en la ciudad. Con su diseño atemporal y comodidad excepcional, estas zapatillas se adaptan a cualquier escenario urbano.",
    precio: 100,
    categoria: "URBAN",
    stock: 5,
  },
  {
    id: 5,
    img: require("./images/img05.png"),
    nombre: "Legacy",
    desc: "Las Legacy son zapatillas que honran el legado del calzado clásico. Su diseño vintage y su construcción robusta son la elección perfecta para quienes valoran la autenticidad y la comodidad.",
    precio: 100,
    categoria: "URBAN",
    stock: 8,
  },
  {
    id: 6,
    img: require("./images/img06.png"),
    nombre: "Heritage",
    desc: "Las Heritage son zapatillas que encarnan la herencia del calzado tradicional. Con un diseño clásico y una calidad excepcional, estas zapatillas son un tributo a la elegancia atemporal.",
    precio: 100,
    categoria: "URBAN",
    stock: 8,
  },
];

export default Data;
